### PR TITLE
[rpc] Fix pending tx & stx fetch

### LINKED ISSUE #2922: [RPC] hmy_pendingTransactions sometimes returns null transactions
Sample output from `hmy_pendingTransactions` from OSTN.
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": [
        null,
        null,
        {
            "blockHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
            "blockNumber": null,
            "from": "one17wv4c2wzagdtjdxyhx0slxrtej34raw3up20uf",
            "timestamp": "0x0",
            "gas": "0x5f15",
            "gasPrice": "0x61a8",
            "hash": "0xfd4e34e03a26f7cf8915d1619459cb69ce89433821785ebe5edd692d25e25e25",
            "input": "0x",
            "nonce": "0x0",
            "to": "one1qfck45kse5qtx7lqfuuvwhelhnjsz2qtdyfysw",
            "transactionIndex": "0x0",
            "value": "0x1144a18dd4735dc100000",
            "shardID": 0,
            "toShardID": 0,
            "v": "0x29",
            "r": "0xebac48a02a41f8c1caa10f2ef3fe0a52abc0c3cf5d5343671df4a771563ed0f6",
            "s": "0x631a65005d30cbee91cb0f14f3eaf6bf39095d03e2c9876d4c3d4385c0fa9b62"
        }
    ]
}
```

### PR DESCRIPTION
**Pull request by Daniel-VDM**
## Issue

This closes #2922 

## Test

Tested locally with multiple txs, here is a screenshot: 
image

## Operational Checklist

1. **Does this PR introduce backward-incompatible changes to the on-disk data structure and/or the over-the-wire protocol?**. (If no, skip to question 8.)

    **NO**

8. **Does this PR introduce backward-incompatible changes *NOT* related to on-disk data structure and/or over-the-wire protocol?** (If no, continue to question 11.)

     **NO**

11. **Does this PR introduce significant changes to the operational requirements of the node software, such as >20% increase in CPU, memory, and/or disk usage?**

     **NO**

### CODE REVIEW

File: internal/hmyapi/apiv1/types.go [hunk 1]
```diff
@@ -157,12 +157,15 @@ func newRPCCXReceipt(cx *types.CXReceipt, blockHash common.Hash, blockNumber uin
...
-func newRPCTransaction(tx *types.Transaction, blockHash common.Hash, blockNumber uint64, timestamp uint64, index uint64) *RPCTransaction {
-	var signer types.Signer = types.FrontierSigner{}
-	if tx.Protected() {
-		signer = types.NewEIP155Signer(tx.ChainID())
+// Note that all txs on Harmony are replay protected (post EIP155 epoch).
+func newRPCTransaction(
+	tx *types.Transaction, blockHash common.Hash,
+	blockNumber uint64, timestamp uint64, index uint64,
+) *RPCTransaction {
+	from, err := types.PoolTransactionSender(types.NewEIP155Signer(tx.ChainID()), tx)
```
Comment (gupadhyaya) [inline internal/hmyapi/apiv1/types.go:165]: will this break for before EIP155? why can't you keep the previous logic to choose different singer?

Comment (Daniel-VDM) [reply internal/hmyapi/apiv1/types.go:165]: We are never in non EIP155 epoch so it will never break, confirmed with @rlan35

File: internal/hmyapi/apiv2/transactionpool.go [hunk 2]
```diff
@@ -362,56 +362,42 @@ func (s *PublicTransactionPoolAPI) GetTransactionReceipt(ctx context.Context, ha
...
-				transactions = append(transactions, newRPCPendingTransaction(plainTx))
-			} else if _, ok := tx.(*staking.StakingTransaction); ok {
-				continue // Do not return staking transactions here
-			} else {
-				return nil, types.ErrUnknownPoolTxType
+	transactions := make([]*RPCTransaction, len(pending))
+	for i := range pending {
+		if plainTx, ok := pending[i].(*types.Transaction); ok {
+			if tx := newRPCTransaction(plainTx, common.Hash{}, 0, 0, 0); tx != nil {
+				transactions[i] = tx
```
Comment (gupadhyaya) [inline internal/hmyapi/apiv2/transactionpool.go:374]: did you try mixed transactions in the pending? index won't be correct, as you skip staking tx here?

Comment (Daniel-VDM) [reply internal/hmyapi/apiv2/transactionpool.go:374]: Right, will swap to list building.

Comment (Daniel-VDM) [reply internal/hmyapi/apiv2/transactionpool.go:374]: https://github.com/harmony-one/harmony/pull/2937
